using OOP;
Time time =new Time() { Hour = 21, Minute = 30, Second=15 };
time.AddHour(10);
time.Print();
time.AddMinute(33); 
time.Print();
time.AddSeconds(127);
time.Print();
time.SubHours(3);
time.Print();
time.SubMinutes(37);
time.Print();
time.SubSeconds(67);
time.Print();
double a = 3;
double b = 4;
double c = 5;
Triangle triangle=new Triangle(a,b,c);
triangle.Print();